### ISSUE TITLE
Profiling support in js-debug

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#388]
We want to explore performance measurement APIs in js-debug. In this month, we plan to:

 - [x] Create a command that could be called by extension plugins to capture profiles
 - [ ] Expose a way for users to capture and save profiles
     - [x] Basic profiling support
     - [x] Rich termination conditions #415
     - [x] Paused and breakpoint state while profiling #416
     - [ ] 💪  Support for capturing heap and tracing-API-based profiles #435
     - [x] Open profiles ~in untitled editors~ on complete #432

 - [x] Investigation into visualization options for the profiles  (tracked in #434)
 - [x] Add an option to start the profiling before the program launches #467

**Comment by connor4312** [comment]
Work will continue in April

**Comment by jasonwilliams** [comment]
Im using 2020.5.1117 and the option doesn't come up for me in the callstack (VSCode stable not insiders) should i be seeing it?

I was reading this https://code.visualstudio.com/updates/v1_45#_new-javascript-debugger and it looks like this options is available.

**Comment by connor4312** [comment]
Make sure that you have the target you want to profile selected. That reminds me that I need to file an issue for that, thanks :)

![](https://memes.peet.io/img/20-05-19049235-346c-4ffe-9883-884a6c21639b.png)

(the child, not the parent, needs to be selected -- then the ⚪ will come up)

**Comment by jasonwilliams** [comment]
My call stack looks like this
![image](https://user-images.githubusercontent.com/936006/81728874-05f83280-9483-11ea-877a-1affbf37c515.png)

**Comment by connor4312** [comment]
It looks like you're using the old debugger. You'll want to turn on the `debug.javascript.usePreview` setting to swap to js-debug.

**Comment by jasonwilliams** [comment]
Oh my bad thanks.
Whats the best way of measuring the start of an app to seeing something on the screen (next.js app), it seems i can only start the recording after a break point is hit. But say i want to measure [appStart -> Breakpoint] is that possible?

**Comment by connor4312** [comment]
You can get the flame graph to show up by clicking the little 🔥 icon on the right of the filter box in the normal table view, or by using the "Reopen With" command.

Startup perf is also something I need to create an issue for. The manual solution right now is to set `stopOnEntry: true` in your launch config and start profiling from there.

**Comment by jasonwilliams** [comment]
ok my issue was that i didn't have the table plugin installed only the flame plugin

**Comment by connor4312** [comment]
Ah, yep. The table is installed by default on insiders but requires manual installation for the moment on stable.

**Comment by jasonwilliams** [comment]
working great now, thanks!

**Comment by LmKupke** [comment]
Can you please put links to the flame plugin and table plugin that need to be installed!

**Comment by connor4312** [comment]
Table: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-js-profile-table
Flame: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-js-profile-flame

**Comment by jasonwilliams** [comment]
I don't know if there's a repo for the flamegraph, but i can't go downwards when viewing.
The scrollwheel expands left and right, and does the same with ctrl|cmd held down. With shift held down it does nothing.

Am i missing something?

**Comment by connor4312** [comment]
Thank you for the feedback on this!

>  Can the scrolling direction be changed to match up with Chrome Performance tab?

fixed in https://github.com/microsoft/vscode-js-profile-visualizer/commit/9cc3d7d

> but maybe something like shift+scroll wheel is enough to scroll vertical

Shift+wheel generally scrolls horizontally, so I made that scroll horizontally and alt+wheel screen vertically

added in https://github.com/microsoft/vscode-js-profile-visualizer/commit/89cb51e

> When i move down to the bottom it stops, but im not sure if its covering some of the flamegraph. Is it possible to add some spacing between the bottom of the flamegraph and the footer of the editor?

added in https://github.com/microsoft/vscode-js-profile-visualizer/commit/848578b

> When i click a bar in the flamegraph it takes me to the file, is there an easy way to go back to where i was without reseting the view?

added in https://github.com/microsoft/vscode-js-profile-visualizer/commit/d663ec2

> Flamegraph is not respecting sourceMapPathOverrides or webRoot

We were looking at `rootPath` for Node, but not the analogous `webRoot` for Chrome, fixed in b6e46d6

**Comment by jasonwilliams** [comment]
That’s incredible work thanks @connor4312!

I had a question about the search bar, what does “start a query()” mean? Is there a query langauge for this? What’s a good way to filter vendor files like node_modules from the view?

**Comment by jasonwilliams** [comment]
> We were looking at rootPath for Node, but not the analogous webRoot for Chrome, fixed in b6e46d6

This one is still not working for me, on the flamegraph i get `./src/components/[componentName].tsx` when i click it it takes me to the `index.js` output rather than the tsx file itself.

**Comment by connor4312** [comment]
> I had a question about the search bar, what does “start a query()” mean? Is there a query langauge for this? What’s a good way to filter out vendor files like node_modules from the view?

There's a basic query 'language' right now ([small docs](https://github.com/microsoft/vscode-js-profile-visualizer/blob/master/query-language.md)). However I plan to remove support for it in favor of a simpler language like the marketplace uses and/or github, for example (this will not work today) you might write `react exclude:node_modules exclude:*.js`. For more advanced visualizer, I plan to explore providing a notebook that allows filtering and transforming data using plain js/ts (with an assortment of helper functions).

> This one is still not working for me, on the flamegraph i get ./src/components/[componentName].tsx when i click it it takes me to the compiled index.js output rather than the tsx file itself.

Thanks, I'll take a look later this week

**Comment by jasonwilliams** [comment]
If i understand correctly the query language doesn't work right now? 
(When i start typing it filters straight away)

**Comment by jasonwilliams** [comment]
It looks like the search in flamegraph view is only searching the top bar, if you search for anything else not at the top (bottom of the stack) it gets filtered out.

Is this intentional?

**Comment by connor4312** [comment]
Not particularly. It will be fixed :)
