### ISSUE TITLE
Master work tracking issue

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#56]
Our first priority is to be able to publish this extension in a form where anyone can install it and use it with their existing node/chrome configs in the same way they are used to, and also try out the new features. In order to publish it to the vscode marketplace, we don't need 100% of the existing features implemented, but it needs to be basically usable, have basic telemetry, and logging for users who report issues.

- [x] Implement basic node/chrome launch configs
- [ ] Implement all launch config flags
  - https://github.com/microsoft/vscode-pwa/issues/26
  - We can start putting it in front of people with many of these boxes unchecked - not sure where we will draw the line exactly
- [x] Implement telemetry
  - Started in https://github.com/microsoft/vscode-pwa/pull/54
  - Include GDPR annotations and publish
- [x] Implement logging
  - https://github.com/microsoft/vscode-pwa/issues/55
- [ ] Stabilize/fill out tests
  - The existing tests are very unstable: https://github.com/microsoft/vscode-pwa/issues/28
  - The imported Chrome integration tests are mostly failing: https://github.com/microsoft/vscode-pwa/issues/44
  - Need to consider bringing over integration tests from node2 as well
- [ ] Decide what to call it and how to communicate the change to users

---

- [ ] CELA Product scan?
- [ ] Security review?

---

Test gaps reported by the VS team, will want to eventually fill these as well: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/2049/JavaScript-debug-adapters-V2?anchor=preliminary-list-of-things-to-test-on-an-integration-level

Feature gaps: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/3608/Comparing-V1-2-to-PWA

**Comment by connor4312** [comment]
This has been mostly completed or in progress in other issues, let's use individual issues and milestones for ongoing work.
